name = "zanile-clipboard"
main = "src/index.ts"
compatibility_date = "2024-05-12"

[[kv_namespaces]]
binding = "NOTES"
id = "3b182a755a0048bf834a600e8cd7f971"
preview_id = "8a6ed224993946a6b9b98099860a9973"

# To use a custom domain in your zone, uncomment and set your zone
# routes = [
#   { pattern = "zanile.com/*", zone_name = "zanile.com" }
# ]

[vars]
DEFAULT_TTL_SECONDS = 2592000 # 30 days
MAX_BYTES = 100000

[[ratelimits]]
name = "WRITE_RATE_LIMITER"
namespace_id = "1001"
[ratelimits.simple]
limit = 10
period = 60

[[analytics_engine_datasets]]
binding = "TRAFFIC"
dataset = "clipboard_traffic"

[observability.logs]
enabled = true
